'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

memo = {}
def fib(n):
    if n in memo:
        return memo[n]
    if n <= 2:
        return n
    f = fib(n-1) + fib(n-2)
    memo[n] = f
    return f
n = 1
sum = 0
while fib(n) <= 4000000:
    f = fib(n)
    if f % 2 == 0:
        sum += f
    n += 1
print(sum)