'''
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''
import math
p = lambda n: n * (3 * n - 1) / 2
p_inv = lambda n: (1 + math.sqrt(1 + 24 * n))/6
def compute():
    D = p(10000)
    for i in range(1,10000):
        for j in range(i, 10000):
            p_i = p(i)
            p_j = p(j)
            if math.floor(p_inv(p_j - p_i)) == p_inv(p_j-p_i) and math.floor(p_inv(p_j + p_i)) == p_inv(p_j+p_i) and abs(p_j - p_i) < D:
                D = abs(p_j - p_i)
    return math.floor(D)
print(compute())
