'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
import math
p_inv = lambda p_n: (1 + math.sqrt(1 + 24 * p_n))/6
h_inv = lambda h_n: (1 + math.sqrt(1 + 8 * h_n))/4
t = lambda n: math.floor(n * (n+1)/2)
def compute():
    i = 286
    while math.floor(p_inv(t(i))) != p_inv(t(i)) or math.floor(h_inv(t(i))) != h_inv(t(i)):
        i += 1
    return t(i)
print(compute())